[package]
name = "oxidized_navigation"
description = "A Nav-Mesh generation plugin for Bevy Engine."
version = "0.2.0"
edition = "2021"

authors = ["TheGrimsey"]
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/TheGrimsey/oxidized_navigation"
repository = "https://github.com/TheGrimsey/oxidized_navigation"

keywords = ["gamedev", "navmesh", "navmesh-generation", "bevy"]
categories = ["game-development"]

[dependencies]
bevy = { version = "0.9", default-features = false }
bevy_rapier3d = { version = "0.20" }
smallvec = { version = "1.10", features = [ "union" ]}
[dev-dependencies]
bevy = { version = "0.9", default-features = false, features = [ "bevy_winit", "render" ] }
futures-lite = "1.12.0"