[package]
name = "oxidized_navigation"
description = "A Nav-Mesh generation plugin for Bevy Engine in Rust."
version = "0.1.0"
edition = "2021"

authors = ["TheGrimsey"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/TheGrimsey/oxidized_navigation"

keywords = ["gamedev", "navmesh", "navmesh-generation"]
categories = ["game-development"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9"
bevy_rapier3d = { version = "0.19" }
smallvec ={ version = "1.10", features = [ "union" ]}
bitflags = "1.3"