[package]
name = "oxidized_navigation"
description = "A Nav-Mesh generation plugin for Bevy Engine."
version = "0.5.2"
edition = "2021"

authors = ["TheGrimsey"]
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/TheGrimsey/oxidized_navigation"
repository = "https://github.com/TheGrimsey/oxidized_navigation"

keywords = ["gamedev", "navmesh", "navmesh-generation", "bevy"]
categories = ["game-development"]

[dependencies]
bevy = { version = "0.10", default-features = false }
bevy_rapier3d = { version = "0.21" }
smallvec = { version = "1.10", features = [ "union" ]}
[dev-dependencies]
bevy = { version = "0.10", default-features = false, features = [ "bevy_winit", "bevy_render", "x11" ] }
bevy_prototype_debug_lines = { version = "0.10", features = ["3d"] }
futures-lite = "1.12.0"
bevy_editor_pls = "0.4.0"